language: python

python:
  - 3.5

addons:
  apt:
    packages:
      - pyqt5-dev-tools

git:
  submodules: false

before_install:
  - git submodule update --init --recursive

install:
  - pip install pyxform

script:

env:
  global:
    # OSGEO credentials to release the plugin
    # Generate with the following command for proper special characters support
    # travis encrypt OSGEO_PASSWORD=\''Your super secret password!'\'
    # TRANSIFEX_API_TOKEN, generated on Transifex website
    # travis encrypt TX_TOKEN="......"

    # GH_TOKEN for creating releases
    # https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line
    # authorize only "public_repo"
    # travis encrypt GH_TOKEN="......"

    # if APPEND_CHANGELOG is defined, a list of all commits since
    # the last release will be appended to the changelog.
    # - APPEND_CHANGELOG=true
