dist: bionic

language: python

python: 3.7

services:
  - docker

jobs:
  include:
    - stage: Run tests Desktop
      name: QGIS Desktop 3.10
      
    before_install:
      - docker pull qgis/qgis:release-3_10

    install:
      - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR} -e DISPLAY=:99 qgis/qgis:release-3_10
      - sleep 10
      - docker exec -it qgis-testing-environment "qgis_setup.sh QRealtime"
    script:
      - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh ./test/test_QRealTime_dialog"

      
